{% set name = "lmod" %}
{% set version = "8.5.22" %}
{% set sha256 = "3553b5c78af153a6d11d765a46d42a4ed0ced28940a8e2618aaf48f492641263" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/TACC/Lmod/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  ## osx build needs https://github.com/conda-forge/lua-feedstock/pull/40 or similar
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - zlib
    - lua
    - luarocks
    - lua-luafilesystem
    - lua-luaposix
    - tk
    - tclreadline
    - pkg-config
  run:
    - libgcc  # [linux]
    - zlib
    - lua
    - luarocks
    - lua-luafilesystem
    - lua-luaposix
    - tk
    - tclreadline

test:
  commands:
    - type module
    - env | grep MODULEPATH_ROOT
    - env | grep MODULEPATH
    - env | grep MODULESHOME

about:
  home: https://github.com/TACC/Lmod
  license: MIT
  license_family: MIT
  license_file: License
  summary: 'Lmod: An Environment Module System based on Lua, Reads TCL Modules, Supports a Software Hierarchy'
  dev_url: https://github.com/TACC/Lmod
  doc_url: http://lmod.readthedocs.org/

extra:
  recipe-maintainers:
    - izahn
    - jerowe
    - izahn
