travis:
  secure:
    BINSTAR_TOKEN: yskPf8SdievRXJVK12Pbf/t/+2rNIUG38FACXGKTINt7+8tmHq2Znpqky+4vcyQev0iUJq2prZyqKcSYvXz2BwcZ0ZfcT0Cvp0Nftv9uRyh9mvn2bJxvnfLv+3G/4UIkSEBQkuVGbh9YlpyGOE3NoPDYd3eL2Y2MWwUvyUS9G5noILDsMvSIA+52JzsKin73rfy8hHUYpWPWATU8XzXwSpGrUdYTEqBrWSdOXhGP5qnHTEzWzWUs9UGIU9wvBInzAEFZeQW4qbPfp3RXxULSv6Rb1eMtJUEfQrw9KHNrd9SrrOAmDbnVXBTSM9Qgs9fBiLDSrx7Y0WWrxuHWwb2gcV9cHGu5VNOv4Nld4+mobb5OcNPYvL20EQkfs1NinXvTbQblvnwsM5Bp6pAvbsVU9GbMf5QpBx3pE+LfZ82M3zcG15YtgimEBUT7t3Zq42FQND7pKFh5llzqhj6VLD2abtbOYc6XSvTSxdnREfrH+mm8oGmFpyi5cPKPxn0sUf68dFWEok/bhPExiGCKMnaQVuPsS7YokQZzY3cpCLtoxFP44MPNafHs+h7amnOvNDHIepOffyTIyUF7X3cazu2ck9GMovwgjkHZ/7csEe53r+SM8WxND1d2tmAPZ9sxqbF62X/QaRkFA1ZNmdwigDFxWcZRlzsdLZbWxChq2vU2AhI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
