travis:
  secure:
    BINSTAR_TOKEN: b7EPGNZmeyUibIPWOHNH+X7NLl1hwd0t53nnLzU3W5Y10qi2p73+afgReLbfB9ve353jT3WIV13JwfDgkWKGdFdyd9zq3oMWkZtz831FnGfoe2IJddMfNTO2emq8E7OqJQFFEtHDC+Of9nl94spriSruojtEhHUSKMW8DX55uPEd6PqRZ4dHZM8PqOfhiuTCOkI1EPTuxF9M2QEfYn56KEJKvA1nlX21bwmvX+fLkS2JPQ9BB8LNzIqDl0NG3tnfPT8orsPiiDMWLvEt3I4xn65sNBB7VbDuaUiP14BULe+PoZSsy1KXg3cfs6XwUXs62W6kfAbSkgnz1l0OO/pQ1bP7UVw81Kq/TByFdxS8kWbVPu5ICFYpIEQy4gSNHk+BZ8n53oi8AIyC8L3ONP7sHJlnfsfguy3QipKRIQgdeXBoFUDZWfIxkgR+A1mRgNsq0qcGIR9LU1cHEVNJc+dIEwJFfoGLXp+WtlEVF/kobVa6N8Xn6utkscxRryIQVIbqFPI3xkGnb1Gi1+KbMi3B0xCWwBu2Vupw6YuFwZM/c64zgR70x+nHkpCEI3j7Mj6d/x3ulUJ6O1qQ635qy4ZxfjFCEm/t1/AAY6ROUG0PO35L+F3LfbjF/yN+7jMyPAGmcJ9g6xtcBNnM2gx0ejTwRvZTJDMiCqlv89v9bZ9W6CA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
